# site settings
title: Tolga Ovaran
subtitle: a Computer Engineer
email: t.ovaran@yahoo.com
description: Hello welcome to my profilio website
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city: Istanbul
state:
zip_code:
country: Turkey
phone: (541) 277-2093

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:h
github_url:
gitlab_url: https://gitlab.com/u/tolgaovaran
googleplus_url: https://www.linkedin.com/in/tolga-ovaran-2b432a117
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/tolga-ovaran-2b432a117
pinterest_url: https://www.linkedin.com/in/tolga-ovaran-2b432a117
slack_url: https://www.linkedin.com/in/tolga-ovaran-2b432a117
twitter_url: https://www.linkedin.com/in/tolga-ovaran-2b432a117

# build settings
markdown: kramdown

sass:
  style: compressed
